site_name: P33tr
site_description: P33tr notes
site_author: Peter Marshall

# nav:
#   - 'index.md'
#   - 'Project Standards': 'project-standards/README.md'
#   - 'Technical Processes': 'technical-processes/README.md'
#   - 'Technical Standards': 'technical-standards/README.md'
#   - 'About': 'About/README.md'


theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
  logo: img/peter_iow_fell_races_small.jpg
  favicon: img/peter_iow_fell_races_small.jpg

  features:
    - navigation.instant
    - navigation.indexes


  palette:
    primary: white
    accent: red
  font:
    text: Karla Regular

# repo_url: https://github.com/p33tr/github.io

# hide the edit button
edit_uri: ""


plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      clickable_checkbox: true


extra_javascript:
   - myscript.js
